export const LOAD_ALL_CLICKS="LOAD_ALL_CLICKS";
export const CLICKS_ADD_FAILED="CLICK_ALL_FAILED";
export const ADD_ALL_CLICKS="ADD_ALL_CLICKS";
export const ADD_ALL_CLICKS_URL="ADD_ALL_CLICKS_URL";

export const GENERATE_ALL_CLICKS_URL_SUCCESSFULL="GENERATE_ALL_CLICKS_URL_SUCCESSFULL";
export const GENERATE_ALL_CLICKS_URL_FAILURE="GENERATE_ALL_CLICKS_URL_FAILURE";

export const GENERATE_CLICKS_THUMBNAILS_SUCCESSFULL="GENERATE_CLICK_THUMBNAILS";
export const GENERATE_CLICKS_THUMBNAILS_FAILURE="GENERATE_CLICK_THUMBNAILS_FAILURE";


export const CREATE_NEW_CLICK="CREATE_NEW_CLICK";
export const UPLOADING_NEW_CLICK="UPLOADING_NEW_CLICK";
export const UPDATE_ALL_CLICKS="UPDATE_ALL_CLICK";
export const UPDATE_ALL_CLICKS_URL="UPDATE_ALL_CLICKS_URL";

export const ATTEMPTING_TO_LOGIN="ATTEMPTING_TO_LOGIN";
export const LOGIN_SUCCESSFULL="LOGIN_SUCCESSFULL";
export const LOGIN_FAILURE="LOGIN_FAILURE";
export const LOGOUT_SUCCESSFULL="LOGOUT_SUCCESSFULL";
export const LOGOUT_FAILURE="LOGOUT_FAILURE";
export const IS_AUTHENTICATED="IS_AUTHENTICATED";

export const LOAD_ALL_COMMENTS="LOAD_ALL_COMMENTS";
export const ADD_ALL_COMMENTS="ADD_ALL_COMMENTS";
export const COMMENTS_ADD_FAILED="COMMENTS_ADD_FAILED";

export const START_EDIT_COMMENT="START_EDIT_COMMENT";
export const EDIT_COMMENT_SUCCESSFULL="EDIT_COMMENT_SUCCESSFULL";
export const EDIT_COMMENT_FAILURE="EDIT_COMMENT_FAILURE";

export const RESET_EDIT_COMMENT_FAILURE_STATE="RESET_EDIT_COMMENT_FAILURE_STATE";
export const RESET_ADD_COMMENT_FAILURE_STATE="RESET_ADD_COMMENT_FAILURE_STATE";


export const START_ADDING_COMMENT="START_ADDING_COMMENT";
export const ADD_COMMENT_SUCCESSFULL="ADD_COMMENT_SUCCESSFULL";
export const ADD_COMMENT_FAILURE="ADD_COMMENT_FAILURE";

export const START_REFRESH_TOKEN="START_REFRESH_TOKEN";
export const REFRESH_TOKEN_SUCCESSFULL="REFRESH_TOKEN_SUCCESSFULL";
export const REFRESH_TOKEN_FAILURE="REFRESH_TOKEN_FAILURE";


export const LOAD_ALL_FAVOURITES="LOAD_ALL_FAVOURITES";
export const ADD_FAVOURITES_SUCCESSFULL="ADD_FAVOURITES_SUCCESSFULL";
export const ADD_FAVOURITES_FAILURE="ADD_FAVOURITES_FAILURE";

export const CHECK_FAVOURITE_SUCCESSFULL="CHECK_FAVOURITE_SUCCESSFULL";
export const CHECK_FAVOURITE_FAILURE="CHECK_FAVOURITE_FAILURE";

export const MAKE_FAVOURITE_SUCCESSFULL="MAKE_FAVOURITE_SUCCESSFULL";
export const MAKE_FAVOURITE_FAILURE="MAKE_FAVOURITE_FAILURE";

export const REMOVE_FAVOURITE_SUCCESSFULL="REMOVE_FAVOURITE_SUCCESSFULL";
export const REMOVE_FAVOURITE_FAILURE="REMOVE_FAVOURITE_FAILURE";






