export const LOAD_ALL_CLICKS="LOAD_ALL_CLICKS";
export const CLICKS_ADD_FAILED="CLICK_ALL_FAILED";
export const ADD_ALL_CLICKS="ADD_ALL_CLICKS";
export const ADD_ALL_CLICKS_URL="ADD_ALL_CLICKS_URL";

export const CREATE_NEW_CLICK="CREATE_NEW_CLICK";
export const UPLOADING_NEW_CLICK="UPLOADING_NEW_CLICK";
export const UPDATE_ALL_CLICKS="UPDATE_ALL_CLICK";
export const UPDATE_ALL_CLICKS_URL="UPDATE_ALL_CLICKS_URL";



